# Generated by Django 4.1.2 on 2022-10-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_empl',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jefedepartamento',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
